{{- if and .Values.minio.enabled .Values.s3www.enabled .Values.uploadJob.cleanupEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "s3www.fullname" . }}-job-cleanup
  labels:
    {{- include "s3www.labels" . | nindent 4 }}
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "s3www.fullname" . }}-job-cleanup
  labels:
    {{- include "s3www.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "s3www.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "s3www.fullname" . }}-job-cleanup
  apiGroup: rbac.authorization.k8s.io
{{- end }}