{{- if .Values.minio.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "s3www.minioFullname" . }}
  labels:
    {{- include "s3www.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.minio.enabled }}
  replicas: {{ .Values.minio.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "s3www.minioSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "s3www.minioSelectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: minio
          image: "{{ .Values.minio.image }}"
          args:
            - server
            - /data
            - "--console-address"
            - ":{{ .Values.minio.consolePort }}"
          ports:
            - containerPort: {{ .Values.minio.port }}
              name: api
            - containerPort: {{ .Values.minio.consolePort }}
              name: console
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.existingSecret | default (printf "%s-credentials" (include "s3www.fullname" .)) }}
                  key: {{ .Values.minio.secretKeys.accessKeyKey }}
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.existingSecret | default (printf "%s-credentials" (include "s3www.fullname" .)) }}
                  key: {{ .Values.minio.secretKeys.secretKeyKey }}
            # - name: MINIO_ROOT_USER
            #   value: "{{ .Values.minio.accessKey }}"
            # - name: MINIO_ROOT_PASSWORD
            #   value: "{{ .Values.minio.secretKey }}"
          volumeMounts:
            - name: minio-storage
              mountPath: /data
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: minio-storage
          persistentVolumeClaim:
            claimName: minio-pvc
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}



