{{- if .Values.s3www.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "s3www.fullname" . }}
  labels:
    {{- include "s3www.labels" . | nindent 4 }}
  {{- with .Values.prometheus.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.s3www.port }}
      protocol: TCP
      name: http
    {{- if .Values.prometheus.metricsPort }}
    - port: {{ .Values.prometheus.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "s3www.selectorLabels" . | nindent 4 }}
{{- end }}


