{{- if and .Values.autoscaling .Values.autoscaling.s3www .Values.autoscaling.s3www.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "s3www.fullname" . }}
  labels:
    {{- include "s3www.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "s3www.fullname" . }}
  minReplicas: {{ .Values.autoscaling.s3www.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.s3www.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.s3www.targetCPUUtilizationPercentage }}
{{- end }}
