{{- if and .Values.minio.enabled (not .Values.minio.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "s3www.fullname" . }}-credentials
  labels:
    {{- include "s3www.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.minio.secretKeys.accessKeyKey }}: {{ .Values.minio.accessKey | b64enc }}
  {{ .Values.minio.secretKeys.secretKeyKey }}: {{ .Values.minio.secretKey | b64enc }}
{{- end }}
