{{- if and .Values.minio.enabled .Values.s3www.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: upload-content-{{ randAlphaNum 5 | lower }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: uploader
          image: minio/mc
          command:
            - /bin/sh
            - -c
            - |
              set -e
              echo {{ .Values.fileToServe | quote }} > /tmp/index.html
              touch /tmp/favicon.ico

              echo "Waiting for MinIO..."
              until mc alias set local http://minio:{{ .Values.minio.port }} {{ .Values.minio.accessKey }} {{ .Values.minio.secretKey }} >/dev/null 2>&1; do
                echo "Still waiting for MinIO..."
                sleep 2
              done

              echo "MinIO is ready. Uploading files..."
              mc mb --ignore-existing local/{{ .Values.minio.bucketName }}
              mc cp /tmp/index.html local/{{ .Values.minio.bucketName }}/index.html
              mc cp /tmp/favicon.ico local/{{ .Values.minio.bucketName }}/favicon.ico

              echo "Upload complete!"
{{- end }}
